# Site settings
title: Hansol's Blog
description: "This is Hansol's Blog"
url: "https://HansolChoe.github.io"
author:
  name: "Hansol Choe"
  email: "hansol614@gmail.com"
  # url: "https://thereviewindex.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "0.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
